name: Add GitHub Release Tag

on:
  push:
    tags:
      - 'plugin-*' # Push events to matching plugin-*, i.e. plugin-(auto-script-jsx|xxx)@1.0.0

# $GITHUB_REF_NAME - https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get pkgName for tag
        id: tag
        run: |
          # matching v2.0.0 / v2.0.0-beta.8 etc
          if [[ $GITHUB_REF_NAME =~ ^v.+ ]]; then
            pkgName="vite"
          else
            # `%@*` truncates @ and version number from the right side.
            # https://stackoverflow.com/questions/9532654/expression-after-last-specific-character
            pkgName=${GITHUB_REF_NAME%@*}
          fi

          echo "::set-output name=pkgName::$pkgName"

      - name: Create Release for Tag
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          # 不需要额外设置, github 默认会每次生成一个
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/Mr-xzq/xzq-vite-plugins/blob/${{ github.ref_name }}/packages/${{ steps.tag.outputs.pkgName }}/CHANGELOG.md) for details.
